### ISSUE TITLE
Allow users to subscribe on new events

### ISSUE THREAD

**Issue by kalabiyau** [kalabiyau/NonSolus#40]
If user in his personal dashboard will tick the check box receive updates - we need to send him email with the details of the new activity which just been created

**Comment by jschmid1** [comment]
- [ ] Tests 
- [ ] Create user dashboard (checkbox)
- [ ] Add migration for subscriber(bool) to User model
- [ ] Adapt Activity controller (send mail to subscriber after creation)
- [ ] Extract information for Activity details for notification mail (ActiveMailer)

**Comment by kalabiyau** [comment]
@jschmid1 *headsup* login now should work with vpn
