### ISSUE TITLE
Create template which will follow proposed design, but do it simply in Bootstrap for index action

### ISSUE THREAD

**Issue by kalabiyau** [kalabiyau/NonSolus#50]
@jschmid1 @thutterer your task, guys. Let's talk a bit about that today/tomorrow

**Comment by kalabiyau** [comment]
@jschmid1 @thutterer some foundational work can be already found in master, but still - a lot to do

**Comment by thutterer** [comment]
check out the branch "design" for the latest development.

**Comment by kalabiyau** [comment]
@thutterer @jschmid1 so far so good!
