### ISSUE TITLE
All pages should show a favicon

### ISSUE THREAD

**Issue by thutterer** [kalabiyau/NonSolus#60]
We should have a favicon. We could use the default SUSE icon but I think it's better to have our own.

**Comment by thutterer** [comment]
As a starting point I quickly created one with [favicon.cc](www.favicon.cc) but GitHub doesn't allow attaching .ICO files here. Will be uploaded to my fork with one of the next commits.

**Comment by thutterer** [comment]
@kalabiyau We want to use the assets pipeline for that, right? Or don't we? Because I just realised there is an empty favicon.ico in ./public

**Comment by thutterer** [comment]
@kalabiyau And another question.. What's the most elegant way to have the same favicon on all pages without coding that in every single view?

**Comment by kalabiyau** [comment]
@thutterer that is a good idea. And I would try to ask @manuelecarlini for the icon.

Generally we should put favicon into assets pipeline and add it to a layout - that way it will be on every page. Assigning to us to make it in 2nd milestone
