### ISSUE TITLE
On small screens layout is broken

### ISSUE THREAD

**Issue by kalabiyau** [kalabiyau/NonSolus#75]

**Comment by thutterer** [comment]
maybe we should do something like this:
http://ironsummitmedia.github.io/startbootstrap-simple-sidebar/
see thread: http://stackoverflow.com/questions/20557912/creating-a-fixed-sidebar-alongside-a-centered-bootstrap-3-grid

**Comment by kalabiyau** [comment]
@thutterer I would suggest you to give it a try and to make a PR with the result so we can evaluate it together

**Comment by thutterer** [comment]
my PR would be a quick fix for this bug until we finish the real layout. ok?
