### ISSUE TITLE
Add new category Hacking

### ISSUE THREAD

**Issue by kalabiyau** [kalabiyau/NonSolus#76]
Choose a good icon from Font awesome

**Comment by thutterer** [comment]
which one do you like better?
http://fortawesome.github.io/Font-Awesome/icon/code/
http://fortawesome.github.io/Font-Awesome/icon/file-code-o/
http://fortawesome.github.io/Font-Awesome/icon/keyboard-o/

**Comment by kalabiyau** [comment]
@thutterer I am keen on http://fortawesome.github.io/Font-Awesome/icon/file-code-o/

**Comment by thutterer** [comment]
@kalabiyau ok. and is there any color pattern i can follow? or should i just pick any color that appears to fit?

**Comment by kalabiyau** [comment]
you can use http://paletton.com/ - select base color as #f36523 and choose anything matching

**Comment by kalabiyau** [comment]
@thutterer cool! BTW, you can now edit your created activity :) Change you category
